# Generated by Django 2.0.2 on 2018-03-08 07:41

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('link', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'verbose_name': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('slug', models.SlugField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Diseases',
                'verbose_name': 'Disease',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thanhphan', models.TextField(blank=True, null=True)),
                ('dangbaoche', models.TextField(blank=True, null=True)),
                ('chidinh', models.TextField(blank=True, null=True)),
                ('lieudung', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Drugs',
                'verbose_name': 'Drug',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experts',
                'verbose_name': 'Expert',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'verbose_name': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'verbose_name': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Positions',
                'verbose_name': 'Position',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('module', models.ManyToManyField(to='core.Module')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('slug', models.SlugField(blank=True, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='module',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='expert',
            name='medicine',
            field=models.ManyToManyField(to='core.Medicine'),
        ),
        migrations.AddField(
            model_name='expert',
            name='module',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='expert',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='drug',
            name='medicine',
            field=models.ManyToManyField(to='core.Medicine'),
        ),
        migrations.AddField(
            model_name='drug',
            name='module',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='drug',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.ManyToManyField(to='core.Medicine'),
        ),
        migrations.AddField(
            model_name='disease',
            name='module',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='disease',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='module',
            field=models.ManyToManyField(to='core.Module'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position'),
        ),
    ]
