# Generated by Django 2.0.2 on 2018-03-15 04:01

import core.models
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(max_length=191)),
                ('s_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('other_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('last_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('slug', core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True)),
                ('seo_name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('seo_desc', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('galery_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('galery_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('galery_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Special Medicine',
                'db_table': 'core_special',
                'verbose_name_plural': 'Special Medicines',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
                ('link', core.models.GeneralCharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.RenameField(
            model_name='expert',
            old_name='seo_name',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='module',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='module',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='module',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='content',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='module',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='seo_desc',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='views',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='module',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='module',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='disease',
            name='s_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='drug',
            name='s_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='disease',
            field=models.ManyToManyField(blank=True, to='core.Disease'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='galery_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='galery_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='galery_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='last_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='other_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='s_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='slug',
            field=core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='drug',
            name='slug',
            field=core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='slug',
            field=core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=core.models.GeneralSlug(blank=True, db_index=True, editable=False, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='special',
            name='disease',
            field=models.ManyToManyField(blank=True, to='core.Disease'),
        ),
        migrations.AddField(
            model_name='special',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
