# Generated by Django 2.0.2 on 2018-03-15 04:13

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180315_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='turns',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
    ]
