# Generated by Django 2.0.2 on 2018-03-19 04:02

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drug_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Danh lục', 'verbose_name_plural': 'Danh lục'},
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='content',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='chidinh',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='content',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dangbaoche',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='lieudung',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='thanhphan',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='content',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='content',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='seo_desc',
            field=core.models.GeneralTextField(blank=True, null=True),
        ),
    ]
