# Generated by Django 2.0.2 on 2018-03-19 06:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drug_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', core.models.GeneralCharField(max_length=191, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Danh lục', 'verbose_name_plural': 'Danh lục'},
        ),
    ]
