# Generated by Django 2.0.2 on 2018-03-20 03:03

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='vi_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='special',
            name='vi_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
    ]
