# Generated by Django 2.0.2 on 2018-03-21 03:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='template',
            field=core.models.GeneralCharField(choices=[('news', 'Layout Bản tin dược liệu'), ('info', 'Layout Thông tin khoa học')], default='news', max_length=191),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vi_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='special',
            name='vi_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
    ]
