# Generated by Django 2.0.2 on 2018-03-21 07:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180321_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='special',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='special',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='chidinh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dangbaoche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='disease',
            field=models.ManyToManyField(related_name='_post_disease_+', to='core.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='galery_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='galery_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='galery_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lieudung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='other_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='s_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thanhphan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vi_name',
            field=core.models.GeneralCharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=core.models.GeneralCharField(choices=[('post', 'Loại tin tức'), ('medicine', 'Loại tra cứu dược liệu'), ('special', 'Loại tra cứu danh lục'), ('drug', 'Loại tra cứu bài thuốc'), ('disease', 'Loại tra cứu bệnh')], default='post', max_length=191),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
    ]
