# Generated by Django 2.0.2 on 2018-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_category_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
