# Generated by Django 2.0.2 on 2018-03-23 07:36

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_is_static'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='disease',
            field=models.ManyToManyField(blank=True, related_name='_post_disease_+', to='core.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.CustomTaggedItem', to='core.MyTag', verbose_name='Tags'),
        ),
    ]
