# Generated by Django 2.0.2 on 2018-03-23 07:41

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_auto_20180323_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaggedItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_customtaggeditembase_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mycustomtag',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.CustomTaggedItemBase', to='core.MyTag', verbose_name='Tags'),
        ),
        migrations.RenameModel(
            old_name='MyTag',
            new_name='MyCustomTag',
        ),
        migrations.AddField(
            model_name='customtaggeditembase',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_customtaggeditembase_items', to='core.MyCustomTag'),
        ),
    ]
