"""
Django settings for site project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from django.conf import settings
from django.utils.translation import gettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@v)bungn*8si*@g!th-y9ft-5jr*v0#9rrkt5@8%nyx(wqtkp='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'filebrowser',
    'django.contrib.admindocs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'frontend',
    'jsoneditor',
    'django_select2',
    'import_export',
    'sorl.thumbnail',
    'taggit',
    'constance',
    'constance.backends.database',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'constance.context_processors.config',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tracuu',
        'USER': 'root',
        'PASSWORD': 'tieungao',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS' : {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/files/'

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "files")

DEFAULT_CHARSET='utf-8'

LOG_FILE = os.path.join(BASE_DIR, 'debug.log')


EXTENSIONS = getattr(settings, "FILEBROWSER_EXTENSIONS", {
    'Image': ['.jpg','.jpeg','.gif','.png','.tif','.tiff', '.JPG','.JPEG','.GIF','.PNG','.tif','.tiff'],
    'Document': ['.pdf','.doc','.rtf','.txt','.xls','.csv'],
    'Video': ['.mov','.wmv','.mpeg','.mpg','.avi','.rm'],
    'Audio': ['.mp3','.mp4','.wav','.aiff','.midi','.m4p']
})

JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.14.0/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.14.0/jsoneditor.css'

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_null_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((None, "-----"), ("yes", "Yes"), ("no", "No"))
    }],
    'ck_editor': ['django.forms.fields.CharField', {
        'widget': 'core.widgets.EditorTextArea',
    }],

    'image_field': ['django.forms.ImageField', {}]
}

CONSTANCE_CONFIG = {
    #'MY_SELECT_KEY': ('yes', 'select yes or no', 'yes_no_null_select'),
    'LOGO_IMAGE': ('default.png', _('Site logo'), 'image_field'),
    'INDEX_TITLE': ('Trang chủ | Tra cứu dược liệu', _('Index title'), str),
    'INDEX_DESC': ('Trang chủ | Tra cứu dược liệu', _('Index Description'), str),
    'INDEX_KEYWORDS': ('Trang chủ | Tra cứu dược liệu', _('Index Keywords'), str),


    'EXPERT_TITLE': ('Chuyên gia | Tra cứu dược liệu', _('Expert title'), str),
    'EXPERT_DESC': ('Chuyên gia | Tra cứu dược liệu', _('Expert Description'), str),
    'EXPERT_KEYWORDS': ('Chuyên gia | Tra cứu dược liệu', _('Expert keywords'), str),
    'EXPERT_CONTENT': ('', _('Expert Content'), 'ck_editor'),
    'EXPERT_IMAGE': ('default.png', _('Expert page image'), 'image_field'),

    'RECOMMEND_TITLE': ('Giới thiệu | Tra cứu dược liệu', _('Recommend title'), str),
    'RECOMMEND_DESC': ('Giới thiệu | Tra cứu dược liệu', _('Recommend Description'), str),
    'RECOMMEND_KEYWORDS': ('Giới thiệu | Tra cứu dược liệu', _('Recommend keywords'), str),
    'RECOMMEND_CONTENT': ('', _('Recommend Content'), 'ck_editor'),
    'RECOMMEND_IMAGE': ('default.png', _('Recommend page image'), 'image_field'),



    'FOOTER_TEXT': ('', _('Footer Text'), str),
    'HEADER_HOTLINE': ('', _('Header Hotline'), str),
    'HEADER_EMAIL': ('', _('Header Email'), str),

    'FB_ID': ('188252524956805', _('Facebook ID'), str),
    'SITE_NAME': (' Tra cứu dược liệu', _('Site name'), str),

    'FACEBOOK_BLOCK_FOOTER': ('', _('Facebook blog footer'), str),
    'GOOGLE': ('', _('Google Analytic'), str),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'General Options': ('LOGO_IMAGE', 'INDEX_TITLE', 'INDEX_DESC', 'INDEX_KEYWORDS',),
    'RECOMMEND Options': ('RECOMMEND_CONTENT', 'RECOMMEND_TITLE', 'RECOMMEND_DESC', 'RECOMMEND_KEYWORDS', 'RECOMMEND_IMAGE'),
    'EXPERT Options': ('EXPERT_CONTENT', 'EXPERT_TITLE', 'EXPERT_DESC', 'EXPERT_KEYWORDS', 'EXPERT_IMAGE'),
    'Header and Footer': ('FOOTER_TEXT', 'HEADER_HOTLINE', 'HEADER_EMAIL', 'FACEBOOK_BLOCK_FOOTER'),
    'Social': ('FB_ID', 'SITE_NAME', 'GOOGLE'),
    #'Theme Options': ('THEME',),
}
#relative path to MEDIA
CKEDITOR_UPLOAD_PATH = "uploads/"
#All uploaded files are slugified by default. To disable this feature
CKEDITOR_UPLOAD_SLUGIFY_FILENAME=False
X_FRAME_OPTIONS = 'SAMEORIGIN'
#CKEDITOR_BROWSE_SHOW_DIRS=True
#CKEDITOR_RESTRICT_BY_DATE=True
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'width': '100%',
        'resize_dir' : 'both',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'resize'
        ]),
    }
}

LABELS =  {
    'name': 'Tiêu đề',
    's_name': 'Tên Khoa Học',
    'other_name': 'Công dụng',
    'category': 'Chuyên mục',
    'last_name': 'Họ',
    'seo_name': 'Tiêu đề dùng cho SEO',
    'seo_desc': 'Mô tả dùng cho SEO',
    'desc': 'Mô tả',
    'content': 'Nội dung',
    'tags': 'Các từ khóa',
    'disease': 'Chọn cho Bệnh',
    'thanhphan': 'Thành phần',
    'dangbaoche': 'Dạng bào chế',
    'lieudung': 'Liều dùng',
    'chidinh': 'Chỉ định',
    'status': 'Trạng thái',
    'vi_name': 'Tên Tiếng Việt',
    'template': 'Chọn layout cho chuyên mục',
}